[theme]
base = "dark"
primaryColor = "#fd6124"
backgroundColor = "#04082c"
secondaryBackgroundColor = "#0b5a92"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
